insert into sites (id, package, zone, zone_name, ward, name, type, category) values
  ('P2-1', 'P2', '1', 'Thiruvottiyur', '1', 'Ennore Express Road near CI Office', 'PCT', 'Major'),
  ('P2-2', 'P2', '1', 'Thiruvottiyur', '1', 'S.V.M. Nagar Burial Ground Road Near CI Office Urinal', 'St. Urinal', 'Major'),
  ('P2-3', 'P2', '1', 'Thiruvottiyur', '1', 'SVM Nagar burial ground', 'PCT', 'Major'),
  ('P2-4', 'P2', '1', 'Thiruvottiyur', '1', 'S.V.M Nagar 9th St', 'PCT', 'Minor'),
  ('P2-5', 'P2', '1', 'Thiruvottiyur', '1', 'Ennore exp road (opp.to Thalankuppam OHT)', 'PCT', 'Major'),
  ('P2-6', 'P2', '1', 'Thiruvottiyur', '1', 'Thalankuppam', 'St. Urinal', 'Already Removed'),
  ('P2-7', 'P2', '1', 'Thiruvottiyur', '1', 'Nettakuppam Main Road Near Community Hall', 'PCT', 'Major'),
  ('P2-8', 'P2', '1', 'Thiruvottiyur', '1', 'Ennore kuppam 3rd St', 'PCT', 'New'),
  ('P2-9', 'P2', '1', 'Thiruvottiyur', '1', 'Mugathuvarakuppam 2nd St', 'PCT', 'New'),
  ('P2-10', 'P2', '1', 'Thiruvottiyur', '1', 'Nettukuppam main road (near 2nd St)', 'PCT', 'Major'),
  ('P2-11', 'P2', '1', 'Thiruvottiyur', '1', 'Nettukuppam 1st St', 'PCT', 'Major'),
  ('P2-12', 'P2', '1', 'Thiruvottiyur', '1', 'Thalankuppam colony road', 'PCT', 'Major'),
  ('P2-13', 'P2', '1', 'Thiruvottiyur', '1', 'Thalankuppam colony road end', 'PCT', 'To Be Removed'),
  ('P2-14', 'P2', '1', 'Thiruvottiyur', '1', 'TNUHDB Tenement Park', 'St. Urinal', 'Already Removed'),
  ('P2-15', 'P2', '1', 'Thiruvottiyur', '1', 'J.J. Nagar near KH road', 'PCT', 'Major'),
  ('P2-16', 'P2', '1', 'Thiruvottiyur', '1', 'J.J. Nagar near Thamarai kulam', 'PCT', 'New'),
  ('P2-17', 'P2', '1', 'Thiruvottiyur', '2', 'Valluvar Nagar', 'PCT', 'Major'),
  ('P2-18', 'P2', '1', 'Thiruvottiyur', '2', 'MGR Nagar', 'PCT', 'Major'),
  ('P2-19', 'P2', '1', 'Thiruvottiyur', '2', 'Sweepers colony', 'PCT', 'Major'),
  ('P2-20', 'P2', '1', 'Thiruvottiyur', '2', 'MTC Bus station', 'St. Urinal', 'To Be Removed'),
  ('P2-21', 'P2', '1', 'Thiruvottiyur', '2', 'K.H Road - Bus Depo', 'PCT', 'Major'),
  ('P2-22', 'P2', '1', 'Thiruvottiyur', '2', 'MTC Depot (Ennore)', 'St. Urinal', 'Already Removed'),
  ('P2-23', 'P2', '1', 'Thiruvottiyur', '2', 'South lock road - Thadavakara kuppam', 'PCT', 'New'),
  ('P2-24', 'P2', '1', 'Thiruvottiyur', '2', 'South lock road', 'PCT', 'Major'),
  ('P2-25', 'P2', '1', 'Thiruvottiyur', '2', 'Kattukuppam 5th street', 'PCT', 'Minor'),
  ('P2-26', 'P2', '1', 'Thiruvottiyur', '2', 'Kattukuppam 1st street', 'PCT', 'Minor'),
  ('P2-27', 'P2', '1', 'Thiruvottiyur', '2', 'UPHC Kathivakkam', 'St. Urinal', 'New'),
  ('P2-28', 'P2', '1', 'Thiruvottiyur', '2', 'Kattivakkam Gandhi Market', 'PCT', 'New'),
  ('P2-29', 'P2', '1', 'Thiruvottiyur', '2', 'Nehru Nagar mendra St', 'PCT', 'New'),
  ('P2-30', 'P2', '1', 'Thiruvottiyur', '2', 'Sasthri Nagar 2nd St', 'PCT', 'Major'),
  ('P2-31', 'P2', '1', 'Thiruvottiyur', '2', 'Anna Nagar 1st', 'PCT', 'Major'),
  ('P2-32', 'P2', '1', 'Thiruvottiyur', '2', 'Chinnakuppam New', 'PCT', 'Major'),
  ('P2-33', 'P2', '1', 'Thiruvottiyur', '2', 'Chinnakuppam', 'PCT', 'Minor'),
  ('P2-34', 'P2', '1', 'Thiruvottiyur', '2', 'Periya kuppam Old (Ennore Express Road)', 'St. Urinal', 'New'),
  ('P2-35', 'P2', '1', 'Thiruvottiyur', '2', 'Periya kuppam near school', 'PCT', 'Minor'),
  ('P2-36', 'P2', '1', 'Thiruvottiyur', '2', 'Periya kuppam new', 'PCT', 'Minor'),
  ('P2-37', 'P2', '1', 'Thiruvottiyur', '2', 'Periya kuppam old', 'PCT', 'New'),
  ('P2-38', 'P2', '1', 'Thiruvottiyur', '3', 'Kathivakkam Railway station road (West)', 'PCT', 'Major'),
  ('P2-39', 'P2', '1', 'Thiruvottiyur', '3', 'Annai sivagami Nagar', 'PCT', 'New'),
  ('P2-40', 'P2', '1', 'Thiruvottiyur', '3', 'Ernavoor kuppam main road', 'PCT', 'New'),
  ('P2-41', 'P2', '1', 'Thiruvottiyur', '3', 'Annai sivagami Nagar 10th street', 'PCT', 'New'),
  ('P2-42', 'P2', '1', 'Thiruvottiyur', '3', 'Kasi Koil kuppam 1st street near seashore', 'PCT', 'Major'),
  ('P2-43', 'P2', '1', 'Thiruvottiyur', '3', 'Kasi Koil kuppam (ladies)', 'PCT', 'New'),
  ('P2-44', 'P2', '1', 'Thiruvottiyur', '3', 'Kasi kovi kuppam bio toilet', 'PCT', 'Major'),
  ('P2-45', 'P2', '1', 'Thiruvottiyur', '3', 'Nethaji Nagar 1st street', 'PCT', 'Major'),
  ('P2-46', 'P2', '1', 'Thiruvottiyur', '3', 'J.J. Nagar 1st street', 'PCT', 'New'),
  ('P2-47', 'P2', '1', 'Thiruvottiyur', '3', 'AIR NAGAR', 'PCT', 'Major'),
  ('P2-48', 'P2', '1', 'Thiruvottiyur', '4', 'Ramanathapuram', 'PCT', 'New'),
  ('P2-49', 'P2', '1', 'Thiruvottiyur', '4', 'Thiruvedhi Amman 5th Street', 'PCT', 'New'),
  ('P2-50', 'P2', '1', 'Thiruvottiyur', '4', 'Manali Express Salai Near Chennai National Hospital', 'St. Urinal', 'New'),
  ('P2-51', 'P2', '1', 'Thiruvottiyur', '4', 'Jothi Nagar Bus Stop Near Daha Street', 'St. Urinal', 'New'),
  ('P2-52', 'P2', '1', 'Thiruvottiyur', '4', 'Murugappa Kulam Jothi Nagar', 'PCT', 'New'),
  ('P2-53', 'P2', '1', 'Thiruvottiyur', '4', 'Jothi Nagar 10th Street Near Amma Unavagam', 'St. Urinal', 'New'),
  ('P2-54', 'P2', '1', 'Thiruvottiyur', '5', 'KVK kuppam', 'PCT', 'Major'),
  ('P2-55', 'P2', '1', 'Thiruvottiyur', '5', 'Bharath Nagar', 'PCT', 'Major'),
  ('P2-56', 'P2', '1', 'Thiruvottiyur', '5', 'MTC Depot (Thiruvottiyur) (Ramakrishna Nagar 3rd Main Road)', 'St. Urinal', 'Major'),
  ('P2-57', 'P2', '1', 'Thiruvottiyur', '5', 'In Front of MRF Open Park Ennore Express Road', 'St. Urinal', 'New'),
  ('P2-58', 'P2', '1', 'Thiruvottiyur', '5', 'WIMCO Nagar', 'PCT', 'New'),
  ('P2-59', 'P2', '1', 'Thiruvottiyur', '5', 'Nethaji Nagar 8th St Link Road', 'PCT', 'New'),
  ('P2-60', 'P2', '1', 'Thiruvottiyur', '6', 'Sathiyamoorthy Nagar Bio Toilet', 'PCT', 'Already Removed'),
  ('P2-61', 'P2', '1', 'Thiruvottiyur', '7', 'Balakrishna Nagar (Hansa Park)', 'St. Urinal', 'New'),
  ('P2-62', 'P2', '1', 'Thiruvottiyur', '7', 'Kirubai Nagar', 'PCT', 'Major'),
  ('P2-63', 'P2', '1', 'Thiruvottiyur', '7', 'Rajaji Nagar', 'PCT', 'Already Removed'),
  ('P2-64', 'P2', '1', 'Thiruvottiyur', '7', 'MGR Nagar', 'PCT', 'Major'),
  ('P2-65', 'P2', '1', 'Thiruvottiyur', '7', 'Periyar Nagar', 'PCT', 'New'),
  ('P2-66', 'P2', '1', 'Thiruvottiyur', '8', 'Masthan Koil', 'PCT', 'Minor'),
  ('P2-67', 'P2', '1', 'Thiruvottiyur', '9', 'Pattinathar Market', 'PCT', 'Minor'),
  ('P2-68', 'P2', '1', 'Thiruvottiyur', '9', 'Thiruvottriyur kuppam (ladies)', 'PCT', 'Major'),
  ('P2-69', 'P2', '1', 'Thiruvottiyur', '9', 'Tiruvattroyur Burial Ground Near', 'PCT', 'Major'),
  ('P2-70', 'P2', '1', 'Thiruvottiyur', '9', 'Appar nagar (ladies)', 'PCT', 'Major'),
  ('P2-71', 'P2', '1', 'Thiruvottiyur', '9', 'Thiruvottriyur kuppam near ennore exp', 'PCT', 'Minor'),
  ('P2-72', 'P2', '1', 'Thiruvottiyur', '10', 'Poonthottam School', 'PCT', 'Minor'),
  ('P2-73', 'P2', '1', 'Thiruvottiyur', '10', 'East tank street', 'PCT', 'Major'),
  ('P2-74', 'P2', '1', 'Thiruvottiyur', '11', 'T.H. Road (Taluka Office)', 'PCT', 'Major'),
  ('P2-75', 'P2', '1', 'Thiruvottiyur', '11', 'T.H. Road Near Taluka Office', 'St. Urinal', 'To Be Removed'),
  ('P2-76', 'P2', '1', 'Thiruvottiyur', '11', 'Poonga Nagar (ladies)', 'PCT', 'Major'),
  ('P2-77', 'P2', '1', 'Thiruvottiyur', '11', 'Kaladipet Sannadhi Street', 'St. Urinal', 'To Be Removed'),
  ('P2-78', 'P2', '1', 'Thiruvottiyur', '11', 'T.H. Road near UPHC', 'PCT', 'Minor'),
  ('P2-79', 'P2', '1', 'Thiruvottiyur', '11', 'Zonal office', 'PCT', 'Minor'),
  ('P2-80', 'P2', '1', 'Thiruvottiyur', '14', 'Ennore Express Road Near Amma Unavagam SBM', 'St. Urinal', 'Major'),
  ('P2-81', 'P2', '1', 'Thiruvottiyur', '14', 'Ennore Express Road Dhobikona', 'PCT', 'New'),
  ('P2-82', 'P2', '1', 'Thiruvottiyur', '14', 'Thiruchinakuppam road', 'PCT', 'New'),
  ('P2-83', 'P2', '2', 'Manali', '15', '80 Feet Road (CMDA Market, Near Bus Stand)', 'PCT', 'Minor'),
  ('P2-84', 'P2', '2', 'Manali', '15', 'Manali new town 150 ft Road, Maha Lakshmi Nagar', 'PCT', 'Minor'),
  ('P2-85', 'P2', '2', 'Manali', '15', 'Manali new town 150 feet Road', 'PCT', 'Major'),
  ('P2-86', 'P2', '2', 'Manali', '15', 'TPP Salai, Near 150 feet Road', 'St. Urinal', 'New'),
  ('P2-87', 'P2', '2', 'Manali', '15', 'New Colony (Nappalayam)', 'PCT', 'New'),
  ('P2-88', 'P2', '2', 'Manali', '15', 'Old nappalayam (old colony)', 'PCT', 'Major'),
  ('P2-89', 'P2', '2', 'Manali', '15', 'Old nappalayam (Vadukarpalayam)', 'PCT', 'Major'),
  ('P2-90', 'P2', '2', 'Manali', '15', 'Edayanchavadi Main Road (Near Anganwadi maiyam)', 'PCT', 'New'),
  ('P2-91', 'P2', '2', 'Manali', '15', 'Edayanchavadi Main Road', 'PCT', 'Major'),
  ('P2-92', 'P2', '2', 'Manali', '15', 'Maha Lakshmi Nagar, Eachangkuzhi', 'PCT', 'Minor'),
  ('P2-93', 'P2', '2', 'Manali', '16', 'Kadapakkam', 'PCT', 'New'),
  ('P2-94', 'P2', '2', 'Manali', '16', 'Kanniamman pet 2', 'PCT', 'Minor'),
  ('P2-95', 'P2', '2', 'Manali', '16', 'Kanniyamman Pet Old Ladies', 'PCT', 'Major'),
  ('P2-96', 'P2', '2', 'Manali', '16', 'Kamarajapuram Radhakrishnan Perumal Koil Street (New)', 'PCT', 'Minor'),
  ('P2-97', 'P2', '2', 'Manali', '16', 'Kamarajapuram Radhakrishnan Perumal Koil Street', 'PCT', 'Major'),
  ('P2-98', 'P2', '2', 'Manali', '16', 'Andarkuppam main road near Ayya Koil', 'St. Urinal', 'To be Removed'),
  ('P2-99', 'P2', '2', 'Manali', '16', 'Elandhanur', 'PCT', 'Minor'),
  ('P2-100', 'P2', '2', 'Manali', '16', 'Sadayankuppam near CMS (New)', 'PCT', 'Minor'),
  ('P2-101', 'P2', '2', 'Manali', '16', 'Sadayankuppam near CMS', 'PCT', 'New'),
  ('P2-102', 'P2', '2', 'Manali', '16', 'Irullar colony (Sadayankuppam)', 'PCT', 'Minor'),
  ('P2-103', 'P2', '2', 'Manali', '16', 'Burma Nagar Burial Ground Road', 'PCT', 'Major'),
  ('P2-104', 'P2', '2', 'Manali', '16', 'Burma Nagar Playground (New)', 'PCT', 'Major'),
  ('P2-105', 'P2', '2', 'Manali', '17', 'Ariyallur Burial Ground', 'PCT', 'Minor'),
  ('P2-106', 'P2', '2', 'Manali', '17', 'Kanniamman Pettai Theeyambakkam', 'PCT', 'Minor'),
  ('P2-107', 'P2', '2', 'Manali', '17', 'Theeyambakkam', 'PCT', 'New'),
  ('P2-108', 'P2', '2', 'Manali', '17', 'Kosapur road Junction', 'St. Urinal', 'To be Removed'),
  ('P2-109', 'P2', '2', 'Manali', '17', 'Thiyagi Viswanatha Dass Nagar Park', 'PCT', 'Park Maintainance'),
  ('P2-110', 'P2', '2', 'Manali', '17', 'Kosappur Bridge Downside', 'PCT', 'Minor'),
  ('P2-111', 'P2', '2', 'Manali', '17', 'Kathakuzhi', 'PCT', 'Minor'),
  ('P2-112', 'P2', '2', 'Manali', '17', 'Kathakuzhi Gents and Ladies Toilet', 'PCT', 'New'),
  ('P2-113', 'P2', '2', 'Manali', '17', 'Perumal Koil street (Vadaperumbakkam)', 'PCT', 'Major'),
  ('P2-114', 'P2', '2', 'Manali', '17', 'Samuvel Nagar', 'PCT', 'New'),
  ('P2-115', 'P2', '2', 'Manali', '17', 'Chinna Thopu(Gents Ladies)', 'PCT', 'Minor'),
  ('P2-116', 'P2', '2', 'Manali', '17', 'Chinna thoppu Ladies', 'PCT', 'Major'),
  ('P2-117', 'P2', '2', 'Manali', '17', 'Periyar Nagar Opp Metro Water Tank', 'PCT', 'New'),
  ('P2-118', 'P2', '2', 'Manali', '17', 'Kosappur Chelliamman Pond', 'PCT', 'New'),
  ('P2-119', 'P2', '2', 'Manali', '18', 'Manali Express Road Opposite to EB Office', 'PCT', 'Major'),
  ('P2-120', 'P2', '2', 'Manali', '18', 'Nedunchezhiyan Street 200 Feet Road', 'PCT', 'Minor'),
  ('P2-121', 'P2', '2', 'Manali', '18', 'Nedunchezhiyan Street Opp to SRF', 'PCT', 'Minor'),
  ('P2-122', 'P2', '2', 'Manali', '18', 'Bharathiyar Street near Burial Ground', 'PCT', 'New'),
  ('P2-123', 'P2', '2', 'Manali', '18', 'Bharathiyar Street near Sivan Koil Temple', 'PCT', 'Major'),
  ('P2-124', 'P2', '2', 'Manali', '19', 'MMDA 2nd Main Road - Park', 'PCT', 'Park Maintainance'),
  ('P2-125', 'P2', '2', 'Manali', '19', 'Kulakarai Street Burial Ground', 'PCT', 'Major'),
  ('P2-126', 'P2', '2', 'Manali', '19', 'Ponniamman koil street (Periya Mathur)', 'PCT', 'Major'),
  ('P2-127', 'P2', '2', 'Manali', '19', 'Ponniyamman Kovil Street Burial Ground', 'PCT', 'Major'),
  ('P2-128', 'P2', '2', 'Manali', '19', 'Ponniyamman Koil Street and Chinna Mathur Salai Junction Near CPCL Nagar', 'PCT', 'Major'),
  ('P2-129', 'P2', '2', 'Manali', '19', 'Manjampakkam Kosappur Junction', 'PCT', 'Major'),
  ('P2-130', 'P2', '2', 'Manali', '19', 'Kamarajar Salai Kalvai Eri Karai Near RRC Point', 'PCT', 'Minor'),
  ('P2-131', 'P2', '2', 'Manali', '19', 'Kosapur Burial Ground', 'PCT', 'Major'),
  ('P2-132', 'P2', '2', 'Manali', '19', 'Junction of Kamarajar Salai Near 16th Day Ceremony Hall', 'PCT', 'Minor'),
  ('P2-133', 'P2', '2', 'Manali', '20', 'Chinna mathur salai near lake park', 'St. Urinal', 'Already Removed'),
  ('P2-134', 'P2', '2', 'Manali', '20', 'Ottravadai Street', 'PCT', 'New'),
  ('P2-135', 'P2', '2', 'Manali', '20', 'Srinivasaperumal Street Burial Ground', 'PCT', 'Minor'),
  ('P2-136', 'P2', '2', 'Manali', '20', 'Kamarajar Salai Near Fire Station', 'PCT', 'Minor'),
  ('P2-137', 'P2', '2', 'Manali', '20', 'Kamarajar Salai Manali Lake Near Amma Unnavagam', 'PCT', 'New'),
  ('P2-138', 'P2', '2', 'Manali', '20', 'Sokkamaal Kolam Street', 'PCT', 'Already Removed'),
  ('P2-139', 'P2', '2', 'Manali', '20', 'Kaal Thottam MGR Street', 'PCT', 'Already Removed'),
  ('P2-140', 'P2', '2', 'Manali', '20', 'Chinnamathur Salai Lake View Near Park', 'PCT', 'New'),
  ('P2-141', 'P2', '2', 'Manali', '21', 'Nedunchezian street (Manali Bus Stand)', 'PCT', 'Major'),
  ('P2-142', 'P2', '2', 'Manali', '21', 'Manali Padasalai', 'Modular Toilet*', 'Already Removed'),
  ('P2-143', 'P2', '2', 'Manali', '21', 'Manali Jalaganda Park', 'Modular Toilet*', 'Already Removed'),
  ('P2-144', 'P2', '2', 'Manali', '21', 'TPP Salai opposite to CPCL Company', 'PCT', 'Already Removed'),
  ('P2-145', 'P2', '2', 'Manali', '21', 'Neducheliyan Salai Opp SRF Gate 1st', 'PCT', 'Already Removed'),
  ('P2-146', 'P2', '2', 'Manali', '21', 'Jalagandam Marriaamman Kovil Street Near Old Police Quarters', 'PCT', 'Already Removed'),
  ('P2-147', 'P2', '2', 'Manali', '22', 'Devaraj Street Inside Community Hall', 'PCT', 'Minor'),
  ('P2-148', 'P2', '2', 'Manali', '22', 'Vazhuthalaimedu Main Road (Open Windrow Method)', 'PCT', 'Minor'),
  ('P2-149', 'P2', '2', 'Manali', '22', 'Open Window Method Inside', 'PCT', 'Minor'),
  ('P2-150', 'P2', '3', 'Madhavaram', '23', 'KS Nagar Main Road', 'PCT', 'Minor'),
  ('P2-151', 'P2', '3', 'Madhavaram', '23', 'S.L.R.Camp', 'St. Bath', 'Major'),
  ('P2-152', 'P2', '3', 'Madhavaram', '23', 'S.L.R.Camp Toilet', 'PCT', 'Major'),
  ('P2-153', 'P2', '3', 'Madhavaram', '23', 'S.L.R.Camp Toilet', 'PCT', 'Major'),
  ('P2-154', 'P2', '3', 'Madhavaram', '23', 'S.L.R.Camp Gents Bath', 'St. Bath', 'Major'),
  ('P2-155', 'P2', '3', 'Madhavaram', '23', 'S.L.R.Camp Ladies Toilet 1', 'PCT', 'Major'),
  ('P2-156', 'P2', '3', 'Madhavaram', '23', 'S.L.R.Camp', 'PCT', 'Already Removed'),
  ('P2-157', 'P2', '3', 'Madhavaram', '23', 'S.L.R.Camp Gents Toilet 1', 'PCT', 'Major'),
  ('P2-158', 'P2', '3', 'Madhavaram', '23', 'S.L.R.Camp Gents and Ladies Toilet', 'PCT', 'To be Removed'),
  ('P2-159', 'P2', '3', 'Madhavaram', '23', 'Subash Chandraboss Street', 'PCT', 'Major'),
  ('P2-160', 'P2', '3', 'Madhavaram', '24', 'Erattaimalai Srinivasan St (Female)', 'PCT', 'Minor'),
  ('P2-161', 'P2', '3', 'Madhavaram', '24', 'Erattaimalai Srinivasan St (Male)', 'PCT', 'Minor'),
  ('P2-162', 'P2', '3', 'Madhavaram', '24', 'Gangadharan St (Ladies)', 'PCT', 'Minor'),
  ('P2-163', 'P2', '3', 'Madhavaram', '24', 'GNT Road Burial Ground', 'PCT', 'Minor'),
  ('P2-164', 'P2', '3', 'Madhavaram', '24', 'Ambattur Redhills Road (Location Changed)', 'PCT', 'Minor'),
  ('P2-165', 'P2', '3', 'Madhavaram', '25', 'MRH Road Inside of Bus Stand', 'PCT', 'Minor'),
  ('P2-166', 'P2', '3', 'Madhavaram', '25', 'Andra Bus Stand', 'PCT', 'Minor'),
  ('P2-167', 'P2', '3', 'Madhavaram', '25', 'CMDA Truck Terminal (Opp to Admin. Building)', 'PCT', 'Minor'),
  ('P2-168', 'P2', '3', 'Madhavaram', '25', 'CMDA Truck Terminal (Northeast Corner)', 'PCT', 'Minor'),
  ('P2-169', 'P2', '3', 'Madhavaram', '25', '200 Feet Road near Valli Bhavan (Location Changed)', 'PCT', 'Minor'),
  ('P2-170', 'P2', '3', 'Madhavaram', '25', 'Thattangulam Road', 'PCT', 'Major'),
  ('P2-171', 'P2', '3', 'Madhavaram', '26', 'Perumal Koil street Edama Nagar MMC road', 'PCT', 'Major'),
  ('P2-172', 'P2', '3', 'Madhavaram', '26', 'Easwaran Koil Street', 'PCT', 'Major'),
  ('P2-173', 'P2', '3', 'Madhavaram', '26', 'Telugu colony Street', 'PCT', 'Major'),
  ('P2-174', 'P2', '3', 'Madhavaram', '26', 'M.G.R. Street (Telugu colony)', 'PCT', 'Major'),
  ('P2-175', 'P2', '3', 'Madhavaram', '26', 'Milk Colony Opp. to GH', 'PCT', 'New'),
  ('P2-176', 'P2', '3', 'Madhavaram', '27', 'M.M.C. pottu room', 'PCT', 'To be Removed'),
  ('P2-177', 'P2', '3', 'Madhavaram', '27', 'Kamaraj Salai (Sastri Nagar Burial Ground)', 'PCT', 'New'),
  ('P2-178', 'P2', '3', 'Madhavaram', '28', 'Periyar Nagar Main Road', 'PCT', 'Minor'),
  ('P2-179', 'P2', '3', 'Madhavaram', '28', 'Ambedhkar Nagar 2nd Main Road', 'PCT', 'Minor'),
  ('P2-180', 'P2', '3', 'Madhavaram', '28', 'Ma Po Vedha St (Gents)', 'PCT', 'Minor'),
  ('P2-181', 'P2', '3', 'Madhavaram', '28', 'Pandian St Old Gents', 'PCT', 'Minor'),
  ('P2-182', 'P2', '3', 'Madhavaram', '28', 'Muthumariamman Koil St (Location Changed) - Amma Unavagam (Ladies)', 'PCT', 'Minor'),
  ('P2-183', 'P2', '3', 'Madhavaram', '28', 'Muthumariamman Koil St', 'PCT', 'Minor'),
  ('P2-184', 'P2', '3', 'Madhavaram', '28', 'Kolkatta shop (Opp to Burial ground)', 'PCT', 'Minor'),
  ('P2-185', 'P2', '3', 'Madhavaram', '28', 'Kannabiran Koil St (Opp to Indital Company)', 'PCT', 'Minor'),
  ('P2-186', 'P2', '3', 'Madhavaram', '28', 'Jangiri shop', 'PCT', 'Minor'),
  ('P2-187', 'P2', '3', 'Madhavaram', '28', 'Maa Po Vedha Street (Back side of Dental Hospital) (Ladies)', 'PCT', 'Minor'),
  ('P2-188', 'P2', '3', 'Madhavaram', '28', 'Pandian St New', 'PCT', 'Minor'),
  ('P2-189', 'P2', '3', 'Madhavaram', '29', 'Vasudeva Mudhali thottam', 'PCT', 'Minor'),
  ('P2-190', 'P2', '3', 'Madhavaram', '29', 'Kalaignar Karunanidhi Street', 'PCT', 'Already Removed'),
  ('P2-191', 'P2', '3', 'Madhavaram', '29', 'E.V.R. Street', 'PCT', 'Already Removed'),
  ('P2-192', 'P2', '3', 'Madhavaram', '29', 'GNT Road Near Adhinath Apartments', 'PCT', 'Already Removed'),
  ('P2-193', 'P2', '3', 'Madhavaram', '30', 'PRH Road Near Jothy Nagar (Location Changed)', 'PCT', 'Minor'),
  ('P2-194', 'P2', '3', 'Madhavaram', '30', 'Vinayagapuram Bus Stand', 'PCT', 'Minor'),
  ('P2-195', 'P2', '3', 'Madhavaram', '30', 'Bharathiyar 1st street', 'PCT', 'To be Removed'),
  ('P2-196', 'P2', '3', 'Madhavaram', '30', 'Madhavaram Roundana-1', 'PCT', 'New'),
  ('P2-197', 'P2', '3', 'Madhavaram', '30', '200 Feet Road', 'PCT', 'New'),
  ('P2-198', 'P2', '3', 'Madhavaram', '30', 'Andhra Bus Terminus', 'PCT', 'Already Removed'),
  ('P2-199', 'P2', '3', 'Madhavaram', '31', 'Padmavathy Nagar Main Road (RRC)', 'PCT', 'New'),
  ('P2-200', 'P2', '3', 'Madhavaram', '31', 'Sembium redhills Road', 'PCT', 'Already Removed'),
  ('P2-201', 'P2', '3', 'Madhavaram', '31', 'Tambaram - Maduravoyal bypass Service Road', 'PCT', 'Already Removed'),
  ('P2-202', 'P2', '3', 'Madhavaram', '32', 'Surapet Burial Ground', 'PCT', 'New'),
  ('P2-203', 'P2', '3', 'Madhavaram', '32', 'Bharathidasan Burial Ground', 'PCT', 'New'),
  ('P2-204', 'P2', '3', 'Madhavaram', '32', 'Parapakulam near Kadapa Road', 'PCT', 'New'),
  ('P2-205', 'P2', '3', 'Madhavaram', '32', 'Thiruvalluvar St', 'PCT', 'Minor'),
  ('P2-206', 'P2', '3', 'Madhavaram', '32', 'Murugambedu Burial Ground', 'PCT', 'Minor'),
  ('P2-207', 'P2', '3', 'Madhavaram', '32', 'Bharath Nagar Burial Ground', 'PCT', 'New'),
  ('P2-208', 'P2', '3', 'Madhavaram', '33', 'Near Ashoka Street Opp to Adhilakshmi Nagar', 'PCT', 'Major'),
  ('P2-209', 'P2', '3', 'Madhavaram', '33', 'Teachers Colony Bus stand', 'PCT', 'Minor'),
  ('P2-210', 'P2', '4', 'Tondiarpet', '34', 'Milk Colony Road (Riswan Road)', 'PCT', 'Minor'),
  ('P2-211', 'P2', '4', 'Tondiarpet', '34', 'Manali Salai', 'PCT', 'Major'),
  ('P2-212', 'P2', '4', 'Tondiarpet', '34', 'Union Carbide colony 14th street', 'St. Urinal', 'To Be Removed'),
  ('P2-213', 'P2', '4', 'Tondiarpet', '34', 'Kaveri Nagar Park', 'St. Urinal', 'To Be Removed'),
  ('P2-214', 'P2', '4', 'Tondiarpet', '35', 'GNT Road', 'PCT', 'To Be Removed'),
  ('P2-215', 'P2', '4', 'Tondiarpet', '35', 'Krishnan street park', 'St. Urinal', 'Already Removed'),
  ('P2-216', 'P2', '4', 'Tondiarpet', '35', 'Muthamizh Nagar 9th street Park', 'St. Urinal', 'Already Removed'),
  ('P2-217', 'P2', '4', 'Tondiarpet', '36', 'EH Road', 'PCT', 'Major'),
  ('P2-218', 'P2', '4', 'Tondiarpet', '36', 'Sharma Nagar 9th street Playground', 'St. Urinal', 'To Be Removed'),
  ('P2-219', 'P2', '4', 'Tondiarpet', '36', 'Papathiamman Koil Street', 'PCT', 'Major'),
  ('P2-220', 'P2', '4', 'Tondiarpet', '36', 'Ambedkar Street', 'PCT', 'Already Removed'),
  ('P2-221', 'P2', '4', 'Tondiarpet', '36', 'Vasuki Nagar Park', 'St. Urinal', 'To Be Removed'),
  ('P2-222', 'P2', '4', 'Tondiarpet', '37', 'MKB Nagar 4th cross street park', 'St. Urinal', 'To Be Removed'),
  ('P2-223', 'P2', '4', 'Tondiarpet', '37', 'Central Avenue Playground', 'St. Urinal', 'To Be Removed'),
  ('P2-224', 'P2', '4', 'Tondiarpet', '37', 'Srinivasan Street (Mahakavi Bharathi Nagar 3rd Main Road)', 'PCT', 'Minor'),
  ('P2-225', 'P2', '4', 'Tondiarpet', '37', 'MKB Nagar 18th cross street', 'PCT', 'Park Maintainance'),
  ('P2-226', 'P2', '4', 'Tondiarpet', '37', 'North avenue road (near bridge)', 'PCT', 'Minor'),
  ('P2-227', 'P2', '4', 'Tondiarpet', '37', 'Jawahar Park', 'PCT', 'Park Maintainance'),
  ('P2-228', 'P2', '4', 'Tondiarpet', '37', 'North avenue road (RRC Center)', 'PCT', 'To Be Removed'),
  ('P2-229', 'P2', '4', 'Tondiarpet', '37', 'Mullai Nagar burial ground', 'St. Urinal', 'New'),
  ('P2-230', 'P2', '4', 'Tondiarpet', '38', 'Parameshwaran Nagar', 'PCT', 'Minor'),
  ('P2-231', 'P2', '4', 'Tondiarpet', '39', 'S.N Chetty street', 'PCT', 'Major'),
  ('P2-232', 'P2', '4', 'Tondiarpet', '39', 'Buchammal street Dobikana', 'PCT', 'New'),
  ('P2-233', 'P2', '4', 'Tondiarpet', '39', 'Butchyammal Street Dobikanna 1', 'PCT', 'Major'),
  ('P2-234', 'P2', '4', 'Tondiarpet', '39', 'Tollgate Bus Stop', 'St. Urinal', 'To Be Removed'),
  ('P2-235', 'P2', '4', 'Tondiarpet', '39', 'A.E Koil street', 'PCT', 'New'),
  ('P2-236', 'P2', '4', 'Tondiarpet', '40', 'A.A. Scheme Road', 'PCT', 'Already Removed'),
  ('P2-237', 'P2', '4', 'Tondiarpet', '40', 'A.E. Koil Street', 'PCT', 'Already Removed'),
  ('P2-238', 'P2', '4', 'Tondiarpet', '41', 'Anna Nagar', 'PCT', 'Major'),
  ('P2-239', 'P2', '4', 'Tondiarpet', '42', 'Thiyagaraya Park, T.H. road', 'St. Urinal', 'To Be Removed'),
  ('P2-240', 'P2', '4', 'Tondiarpet', '42', 'Kailasam Street', 'PCT', 'Minor'),
  ('P2-241', 'P2', '4', 'Tondiarpet', '42', 'T.H. Road Service Road', 'PCT', 'New'),
  ('P2-242', 'P2', '4', 'Tondiarpet', '42', 'Illaya Street', 'St. Urinal', 'Already Removed'),
  ('P2-243', 'P2', '4', 'Tondiarpet', '42', 'In front of Rettai Kuli Street', 'St. Urinal', 'Already Removed'),
  ('P2-244', 'P2', '4', 'Tondiarpet', '42', 'Jeeva park', 'St. Urinal', 'To Be Removed'),
  ('P2-245', 'P2', '4', 'Tondiarpet', '42', 'Pitty munusamy Street', 'PCT', 'Minor'),
  ('P2-246', 'P2', '4', 'Tondiarpet', '43', '16AA.D Road Tondiarpet Ch- 81', 'PCT', 'Already Removed'),
  ('P2-247', 'P2', '4', 'Tondiarpet', '43', '97, New Amarajipuram, Royapuram Ch-13', 'PCT', 'Minor'),
  ('P2-248', 'P2', '4', 'Tondiarpet', '43', 'SN Chetty street (Near Park)', 'St. Urinal', 'To Be Removed'),
  ('P2-249', 'P2', '4', 'Tondiarpet', '43', '43/A S.N Chetty Street, Ch- 13', 'PCT', 'Minor'),
  ('P2-250', 'P2', '4', 'Tondiarpet', '43', 'S.N. Chetty street', 'St. Urinal', 'Already Removed'),
  ('P2-251', 'P2', '4', 'Tondiarpet', '43', '(Thedeer Nagar) S.N Chetty Street, Ch-13', 'PCT', 'Major'),
  ('P2-252', 'P2', '4', 'Tondiarpet', '43', 'CD Hospital Phase-I', 'PCT', 'Already Removed'),
  ('P2-253', 'P2', '4', 'Tondiarpet', '43', 'CD Hospital Phase-II', 'PCT', 'Already Removed'),
  ('P2-254', 'P2', '4', 'Tondiarpet', '44', 'MPM street Jn of Kamarajar 1st street', 'St. Urinal', 'Already Removed'),
  ('P2-255', 'P2', '4', 'Tondiarpet', '44', 'Sathyavani Muthu Nagar Park', 'St. Urinal', 'To Be Removed'),
  ('P2-256', 'P2', '4', 'Tondiarpet', '45', 'Desikananda park', 'St. Urinal', 'To Be Removed'),
  ('P2-257', 'P2', '4', 'Tondiarpet', '45', 'Sastri Nagar 16th Street', 'PCT', 'Already Removed'),
  ('P2-258', 'P2', '4', 'Tondiarpet', '45', 'Melpatti Ponnappan Street', 'PCT', 'Major'),
  ('P2-259', 'P2', '4', 'Tondiarpet', '45', 'BV Colony 8th Street (5th St)', 'PCT', 'New'),
  ('P2-260', 'P2', '4', 'Tondiarpet', '46', 'Street End, Moorthinagar Street (Junction)', 'PCT', 'Major'),
  ('P2-261', 'P2', '4', 'Tondiarpet', '46', 'Moorthingar Street', 'PCT', 'Minor'),
  ('P2-262', 'P2', '4', 'Tondiarpet', '46', 'Street End, John Kennady Nagar', 'PCT', 'Major'),
  ('P2-263', 'P2', '4', 'Tondiarpet', '46', 'Good Shed Road, Samanthi Poo Colony', 'PCT', 'Minor'),
  ('P2-264', 'P2', '4', 'Tondiarpet', '46', 'Malligai Poo Colony', 'PCT', 'Minor'),
  ('P2-265', 'P2', '4', 'Tondiarpet', '46', 'C. Kalyanapuram', 'PCT', 'Already Removed'),
  ('P2-266', 'P2', '4', 'Tondiarpet', '46', 'Corporation Higher Secondary School Near, SM Nagar Main Road', 'PCT', 'Major'),
  ('P2-267', 'P2', '4', 'Tondiarpet', '46', 'Gandhipuram', 'PCT', 'Major'),
  ('P2-268', 'P2', '4', 'Tondiarpet', '46', 'Gandhipuram', 'PCT', 'Minor'),
  ('P2-269', 'P2', '4', 'Tondiarpet', '46', 'Samandhi Poo Playground', 'St. Urinal', 'To Be Removed'),
  ('P2-270', 'P2', '4', 'Tondiarpet', '46', 'Sathyamurthy Nagar Park', 'St. Urinal', 'To Be Removed'),
  ('P2-271', 'P2', '', '', '', 'JJ Nagar 1st Street', 'PCT', 'Already Removed'),
  ('P2-272', 'P2', '4', 'Tondiarpet', '47', 'J.J Nagar Ladies', 'PCT', 'Already Removed'),
  ('P2-273', 'P2', '4', 'Tondiarpet', '47', 'J.J. Nagar', 'PCT', 'New'),
  ('P2-274', 'P2', '4', 'Tondiarpet', '47', 'Kamaraj Nagar 7th Street', 'PCT', 'To be Removed'),
  ('P2-275', 'P2', '4', 'Tondiarpet', '47', 'Kamaraj Nagar 2nd Street', 'PCT', 'To be Removed'),
  ('P2-276', 'P2', '4', 'Tondiarpet', '47', 'Meenabal Nagar Cross St', 'PCT', 'New'),
  ('P2-277', 'P2', '4', 'Tondiarpet', '47', 'Harinarayanapuram (Pumping Station) Ladies', 'PCT', 'New'),
  ('P2-278', 'P2', '4', 'Tondiarpet', '47', 'Harinarayanapuram Pumping Station Opposite Gents Toilet', 'PCT', 'To be Removed'),
  ('P2-279', 'P2', '4', 'Tondiarpet', '47', 'Harinarayanapuram (C.B Road)', 'PCT', 'Major'),
  ('P2-280', 'P2', '4', 'Tondiarpet', '47', 'Amma ECO park (Oswal garden park), CB road', 'St. Urinal', 'Already Removed'),
  ('P2-281', 'P2', '4', 'Tondiarpet', '48', 'Venkatakrishnan Street', 'PCT', 'To Be Removed'),
  ('P2-282', 'P2', '4', 'Tondiarpet', '48', 'Kanni Koil street (Venkatakrishnan Street)', 'St. Urinal', 'Already Removed'),
  ('P2-283', 'P2', '4', 'Tondiarpet', '48', 'Nainiappan Street', 'PCT', 'Already Removed'),
  ('P2-284', 'P2', '4', 'Tondiarpet', '48', 'Parthasarathy Street', 'PCT', 'Minor'),
  ('P2-285', 'P2', '4', 'Tondiarpet', '48', 'Telugu Chetty street (Park)', 'St. Urinal', 'To Be Removed'),
  ('P4-1', 'P4', '11', 'Valasaravakkam', '145', 'Nerkundram Playground, Perumal kovil Street Near Nadhan School', 'PCT', 'Minor'),
  ('P4-2', 'P4', '11', 'Valasaravakkam', '147', 'Ganga Nagar, Gandhi Street', 'PCT', 'Minor'),
  ('P4-3', 'P4', '11', 'Valasaravakkam', '155', 'Rayala Nagar', 'PCT', 'Minor'),
  ('P4-4', 'P4', '11', 'Valasaravakkam', '149', 'Kalaignar ground ramakrishna nagar tagore street', 'PCT', 'Major'),
  ('P4-5', 'P4', '11', 'Valasaravakkam', '151', 'Lakshmi nagar extension 4th main road porur', 'PCT', 'Minor'),
  ('P4-6', 'P4', '11', 'Valasaravakkam', '152', 'Chowdry nagar main road', 'PCT', 'Major'),
  ('P4-7', 'P4', '11', 'Valasaravakkam', '152', 'Bharathi colony kaikkankuppam ramapuram', 'PCT', 'Minor'),
  ('P4-8', 'P4', '11', 'Valasaravakkam', '149', 'Bridhavanan Nagar 6th St, Valasaravakkam', 'PCT', 'Minor'),
  ('P4-9', 'P4', '11', 'Valasaravakkam', '151', 'Arcot Road, Porur, BG', 'PCT', 'Minor'),
  ('P4-10', 'P4', '12', 'Alandur', '156', 'Rajeshwari avenue madhanandhapuram', 'PCT', 'Minor'),
  ('P4-11', 'P4', '12', 'Alandur', '167', 'Nanganallur, Skating Rink', 'PCT', 'Minor'),
  ('P4-12', 'P4', '12', 'Alandur', '162', 'Kannan colony burial ground', 'PCT', 'Minor'),
  ('P4-13', 'P4', '12', 'Alandur', '156', 'Kundrumedu burial ground', 'PCT', 'Major'),
  ('P4-14', 'P4', '12', 'Alandur', '163', 'Bala Krishna Puram', 'PCT', 'Minor'),
  ('P4-15', 'P4', '12', 'Alandur', '163', 'New Colony, Adambakkam', 'PCT', 'Major'),
  ('P4-16', 'P4', '12', 'Alandur', '165', 'VANUVAMPETTAI', 'PCT', 'Minor'),
  ('P4-17', 'P4', '13', 'Adyar', '173', 'Indra nagar,8th cross street,adyar,chennai-20', 'PCT', 'Minor'),
  ('P4-18', 'P4', '13', 'Adyar', '174', 'No:12, 3rd avenue besant nagar,chennai-90', 'PCT', 'Minor'),
  ('P4-19', 'P4', '13', 'Adyar', '175', 'Sastri nagar 4th street, adambakkam,chennai-88', 'PCT', 'Minor'),
  ('P4-20', 'P4', '13', 'Adyar', '175', 'Shawwalace colony 2nd street,adambakkam,chennai-88', 'PCT', 'Minor'),
  ('P4-21', 'P4', '13', 'Adyar', '175', 'Dr.ambedkar nagar 1st main,adambakkam,chennai-88', 'PCT', 'Major'),
  ('P4-22', 'P4', '13', 'Adyar', '177', 'Bethal avenue main road,velachery,chennai-42', 'PCT', 'Minor'),
  ('P4-23', 'P4', '13', 'Adyar', '180', '7th cross street, thiruvalluvar nagar, thiruvanmyur,, chennai -41', 'PCT', 'Minor'),
  ('P4-24', 'P4', '13', 'Adyar', '168', 'Arulayammanpettai, Guindy', 'PCT', 'Major'),
  ('P4-25', 'P4', '13', 'Adyar', '168', 'Guindy Estate SIDCO', 'PCT', 'Major'),
  ('P4-26', 'P4', '13', 'Adyar', '170', 'Suriya Nagar Ranjith Road, Adyar', 'PCT', 'Minor'),
  ('P4-27', 'P4', '13', 'Adyar', '170', 'Erikarai Street, Kottur, Adyar', 'PCT', 'Minor'),
  ('P4-28', 'P4', '13', 'Adyar', '172', 'Velachery Main Road, Gurunanak College', 'PCT', 'Minor'),
  ('P4-29', 'P4', '13', 'Adyar', '178', 'Velachery Main Road, Bharathi Nagar (Tharamani Road)', 'PCT', 'Major'),
  ('P4-30', 'P4', '13', 'Adyar', '180', 'Thiruvalluvar Nagar 7th Cross Street Extension', 'PCT', 'Minor'),
  ('P4-31', 'P4', '14', 'Perungudi', '181', 'AGS Colony Beach Main Road(Kuppam),Kottivakkam', 'PCT', 'Major'),
  ('P4-32', 'P4', '14', 'Perungudi', '181', 'AGS colony 2nd main road,kottivakkam', 'PCT', 'Minor'),
  ('P4-33', 'P4', '14', 'Perungudi', '185', 'Kuppusamy street,Ullagaram', 'PCT', 'Minor'),
  ('P4-34', 'P4', '14', 'Perungudi', '189', 'Kamakotti Nagar 6th Street,Pallikaranai', 'PCT', 'Minor'),
  ('P4-35', 'P4', '14', 'Perungudi', '189', 'VGP Shanthi Nagar,Santhosh Street,Pallikaranai', 'PCT', 'Minor'),
  ('P4-36', 'P4', '14', 'Perungudi', '189', 'Kamakotti Nagar 4th Street,Pallikaranai', 'PCT', 'Minor'),
  ('P4-37', 'P4', '14', 'Perungudi', '181', 'VENKATESHWARA NAGAR BURIAL GROUND', 'PCT', 'Major'),
  ('P4-38', 'P4', '14', 'Perungudi', '183', 'PALAVAKKAM BURIAL GROUND', 'PCT', 'Minor'),
  ('P4-39', 'P4', '14', 'Perungudi', '185', 'USHA NAGAR', 'PCT', 'Minor'),
  ('P4-40', 'P4', '14', 'Perungudi', '186', 'PUZHUTHIVAKKAM BURIAL GROUND', 'PCT', 'Minor'),
  ('P4-41', 'P4', '14', 'Perungudi', '190', 'KOVALAN NAGAR MAIN ROAD', 'PCT', 'Minor'),
  ('P4-42', 'P4', '14', 'Perungudi', '191', 'GRAMA MAYANA BOOMI', 'PCT', 'Minor'),
  ('P4-43', 'P4', '15', 'Sholinganallur', '195', 'Chandrasekar Avenue, Okkiyam Thuraipakkam, OMR', 'PCT', 'Minor'),
  ('P4-44', 'P4', '15', 'Sholinganallur', '199', 'Sholinganallur TNHB A Road', 'PCT', 'Minor'),
  ('P4-45', 'P4', '15', 'Sholinganallur', '200', 'Semmancherry Tsunami nagar 1st Main Road', 'PCT', 'Minor'),
  ('P4-46', 'P4', '15', 'Sholinganallur', '192', 'Neelankarai Village Burial Ground, Kabaleeswarar Nagar Beach Main Road', 'PCT', 'Minor'),
  ('P4-47', 'P4', '15', 'Sholinganallur', '194', 'Harichandra Salai Burial Ground, Injampakkam', 'PCT', 'Minor'),
  ('P4-48', 'P4', '15', 'Sholinganallur', '195', 'Mettukuppam Rajiv Nagar Burial Ground', 'PCT', 'Major'),
  ('P4-49', 'P4', '15', 'Sholinganallur', '198', 'Kuppuisamy street hindu Burial ground', 'PCT', 'Minor'),
  ('P4-50', 'P4', '15', 'Sholinganallur', '198', 'Kuppuisamy street Karapakkam Burial ground Opp to Compost yard', 'PCT', 'Minor'),
  ('P4-51', 'P4', '15', 'Sholinganallur', '198', 'Karapakkam Burial ground Karapakkam, (Burial and cremeation)', 'PCT', 'Minor'),
  ('P4-52', 'P4', '15', 'Sholinganallur', '199', 'TNHB C12 Road Burial Ground Shozhinganallur', 'PCT', 'Minor'),
  ('P4-53', 'P4', '15', 'Sholinganallur', '200', 'Veeravanchinathan Street Burial Ground, Chemmancherry', 'PCT', 'Minor'),
  ('P4-54', 'P4', '15', 'Sholinganallur', '200', 'Village Burial Ground, OMR, Chemmancherry (Mayana Salai )', 'PCT', 'Minor'),
  ('P4-55', 'P4', '11', 'Valasaravakkam', '153', 'Under MGR Flyover MPH Road', 'PCT', 'Minor'),
  ('P4-56', 'P4', '13', 'Adyar', '179', 'Besant Nagar 6th Avenue near skating ground', '', 'E-Toilet / Minor'),
  ('P4-57', 'P4', '13', 'Adyar', '168', 'Kathipara Road (Near Post Office)', 'PCT', 'Minor'),
  ('P4-58', 'P4', '15', 'Sholinganallur', '200', 'Dn- Office Palathotta Salai', '', 'PCt / New Toilet'),
  ('P4-59', 'P4', '15', 'Sholinganallur', '196', 'Kannagi Nagar ETR Main road, Near Police Station Opposite', '', 'Minor'),
  ('P4-60', 'P4', '15', 'Sholinganallur', '194', 'Amma Unnavagam Mahathma Gandhi 1st Main road', 'PCT', 'Major'),
  ('P4-61', 'P4', '15', 'Sholinganallur', '194', 'V.O.C Street', 'PCT', 'Major'),
  ('P4-62', 'P4', '15', 'Sholinganallur', '194', 'Near Division Office', 'PCT', 'Major'),
  ('P4-63', 'P4', '15', 'Sholinganallur', '194', 'UCHC Hospital', 'PCT', 'Minor'),
  ('P4-64', 'P4', '15', 'Sholinganallur', '194', 'Ankanvadi School (Children Toilet)', 'PCT', 'Minor'),
  ('P4-65', 'P4', '11', 'Valasaravakkam', '143', 'Sri Ram Nagar Main road Near Sriram nagar bus stand', 'PCT', 'Minor / Demolished / New Toilet'),
  ('P4-66', 'P4', '11', 'Valasaravakkam', '144', 'Near Poonamallee road (Nagaathaamman Kovil Street)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-67', 'P4', '11', 'Valasaravakkam', '144', 'Near VGP Amutha nagar (Pillaiyar Kovil Street)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-68', 'P4', '11', 'Valasaravakkam', '145', 'Near Church (New Colony 3rd Street)', 'PCT', 'Minor / Minor / New Toilet'),
  ('P4-69', 'P4', '11', 'Valasaravakkam', '149', 'Sridevikuppam main road', 'PCT', 'Minor / Minor / Minor'),
  ('P4-70', 'P4', '11', 'Valasaravakkam', '150', 'Opp to porur lake (Gandhi Nagar)', 'PCT', 'Minor / Minor / New Toilet'),
  ('P4-71', 'P4', '11', 'Valasaravakkam', '152', 'Thiruvalluvar Salai Near Amma Unavagam Alternate site - Arcot road - Zonal office', 'PCT', 'Minor / Minor / Minor'),
  ('P4-72', 'P4', '11', 'Valasaravakkam', '143', 'Vembuliamman nagar', 'PCT', 'New proposal / NA / New Toilet'),
  ('P4-73', 'P4', '11', 'Valasaravakkam', '143', 'Madha koil street', 'PCT', 'New proposal / NA / New Toilet'),
  ('P4-74', 'P4', '11', 'Valasaravakkam', '145', 'Bone factory road inside burial ground', 'PCT', 'New proposal / NA / New Toilet'),
  ('P4-75', 'P4', '11', 'Valasaravakkam', '148', 'Kamarajar high road', 'PCT', 'New proposal / NA / New Toilet'),
  ('P4-76', 'P4', '11', 'Valasaravakkam', '145', 'Nerkundram Playground , Perumal kovil Street Near Nadhan School', 'PCT', 'Minor'),
  ('P4-77', 'P4', '12', 'Alandur', '156', 'Mugalivakkam road, Manapakkam main road', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-78', 'P4', '12', 'Alandur', '156', 'Othavadi street', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-79', 'P4', '12', 'Alandur', '156', 'Madhanandapuram main road', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-80', 'P4', '12', 'Alandur', '157', 'Girigori Nagar Girigori Nagar Near Church', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-81', 'P4', '12', 'Alandur', '157', 'Purachithalaivi nagar', 'PCT', 'Minor / Major / New Toilet'),
  ('P4-82', 'P4', '12', 'Alandur', '157', 'Periya colony', 'PCT', 'Major / Major / New Toilet'),
  ('P4-83', 'P4', '12', 'Alandur', '158', 'Ramar kovil street, near metro water tank', 'PCT', 'Minor / Major / New Toilet'),
  ('P4-84', 'P4', '12', 'Alandur', '159', 'Pandian Street Near Meenampakkam Subway', 'PCT', 'Minor / Major / New Toilet'),
  ('P4-85', 'P4', '12', 'Alandur', '159', 'VOC Street', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-86', 'P4', '12', 'Alandur', '159', 'Anna street', 'PCT', 'Minor / Minor / New Toilet'),
  ('P4-87', 'P4', '12', 'Alandur', '160', 'Margoes Street Margoes street, Near EB office', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-88', 'P4', '12', 'Alandur', '161', 'Raja street', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-89', 'P4', '12', 'Alandur', '161', 'VOC Nagar', 'PCT', 'Minor / Major / MINOR'),
  ('P4-90', 'P4', '12', 'Alandur', '162', 'Thillai Ganga Nagar Burial Ground', 'PCT', 'Minor / Minor
(Closed) / Major'),
  ('P4-91', 'P4', '12', 'Alandur', '162', 'Thillai Ganga Nagar 4th Main Road', '', 'Namma
Toilet / Minor / Major / MINOR'),
  ('P4-92', 'P4', '12', 'Alandur', '162', 'Marrison street', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-93', 'P4', '12', 'Alandur', '162', 'NOBLE STREET (2) (1st Street)', '', 'E-Toilet / Minor / Minor / Minor'),
  ('P4-94', 'P4', '12', 'Alandur', '162', 'Kannan colony', 'PCT', 'Major / Major / New Toilet'),
  ('P4-95', 'P4', '12', 'Alandur', '163', 'Mannadiamman koil street', 'PCT', 'Minor / Minor / New Toilet'),
  ('P4-96', 'P4', '12', 'Alandur', '164', 'NEHRU COLONY', '', 'E-Toilet / Minor / Major (No
Stability) / New Toilet'),
  ('P4-97', 'P4', '12', 'Alandur', '164', 'Nanganallur V main road near Jaigopal Garodia school', '', 'Standalone
Urinal / Minor / Minor / MINOR'),
  ('P4-98', 'P4', '12', 'Alandur', '164', '(Relocated to 4th Main Road) Nanganallur Ist main road II main road Junction', '', 'Standalone
Urinal / Minor / Major (No
Stability) / New Toilet'),
  ('P4-99', 'P4', '12', 'Alandur', '165', 'Nanganallur 11th street', 'PCT', 'Minor / Minor
(Closed) / MINOR'),
  ('P4-100', 'P4', '12', 'Alandur', '165', 'RAM NAGAR 2nd STREET ANJANEYAR TEMPLE', '', 'E-Toilet / Minor / Major (No
Stability) / Major'),
  ('P4-101', 'P4', '12', 'Alandur', '165', 'INDRA NAGAR 2nd STREET', '', 'E-Toilet / Minor / Major (No
Stability) / MINOR'),
  ('P4-102', 'P4', '12', 'Alandur', '166', 'NEAR GANDHI NAGAR AMMA CANTEEN', '', 'E-Toilet / Minor / Minor / MINOR'),
  ('P4-103', 'P4', '12', 'Alandur', '166', 'B.V.Nagar 3rd main road Burma Tamilar Colony', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-104', 'P4', '12', 'Alandur', '166', 'Nehru Nedunchalai', 'PCT', 'Minor / Minor / MINOR'),
  ('P4-105', 'P4', '12', 'Alandur', '166', 'NEAR STATE BANK COLONY PARK', '', 'E-Toilet / Minor / Minor (No
Stability) / MINOR'),
  ('P4-106', 'P4', '12', 'Alandur', '164', 'NANGA NALLUR 48th STREET', '', 'E-Toilet / Minor / Minor / MINOR'),
  ('P4-107', 'P4', '12', 'Alandur', '167', 'Nanganallur 6th main road near Indian bank', '', 'Standalone
Urinal / Minor / Major (No
Stability) / Minor'),
  ('P4-108', 'P4', '12', 'Alandur', '167', '100 Ft Road', '', 'E-Toilet / Minor / Not Found / Minor'),
  ('P4-109', 'P4', '12', 'Alandur', '167', 'Kannan nagar II main road near Movarasampettai tank', '', 'Standalone
Urinal / Minor / Major (No
Stability) / Minor'),
  ('P4-110', 'P4', '12', 'Alandur', '167', 'NANGANALLUR BUS STAND', '', 'E-Toilet / Minor / Minor / Minor'),
  ('P4-111', 'P4', '12', 'Alandur', '167', 'VOLTAS COLONY PARK', '', 'E-Toilet / Minor / Minor
(Closed) / Minor'),
  ('P4-112', 'P4', '13', 'Adyar', '168', 'Nerupumedu', 'PCT', 'Minor / Minor / Minor'),
  ('P4-113', 'P4', '13', 'Adyar', '169', '(Relocated to Taluk Office Road) Gandhi Mandapam Road Near Birla Planetarium', 'PCT', 'Minor / Minor / Minor'),
  ('P4-114', 'P4', '13', 'Adyar', '169', 'Sardar Patel Road Gandhi Mandapam Bus Stop (Relocated To Dn 168 SIDCO Industrial Estate Guindy Bus Stand)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-115', 'P4', '13', 'Adyar', '170', 'Sardar Patel Road Madhya Kailash Temple (Back Side Park)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-116', 'P4', '13', 'Adyar', '170', 'Chitra Nagar', 'PCT', 'Major / Minor / Major'),
  ('P4-117', 'P4', '13', 'Adyar', '168', 'Kathipara Road Theerachinnur Store', 'PCT', 'Minor / Minor / Minor'),
  ('P4-118', 'P4', '13', 'Adyar', '168', 'Kathipara Road (For Physically Challenged)', 'PCT', 'Minor / Minor / MInor'),
  ('P4-119', 'P4', '13', 'Adyar', '168', 'Reddy II Street', 'PCT', 'Minor / Minor / Minor'),
  ('P4-120', 'P4', '13', 'Adyar', '170', 'Soorya nagar', 'PCT', 'Major / Minor / Minor'),
  ('P4-121', 'P4', '13', 'Adyar', '171', '(R.K.Nagar 1 St Main Road) South Canal Bank Road (Rajagramani Thottam) (Relocated to RA Puram Kamarajar Salai) (R.K.Nagar 1 St Main Road)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-122', 'P4', '13', 'Adyar', '171', 'Thandavarayan Street (Relocated To MRC Nagar - Janaki Avenue`)', 'PCT', 'Major / Minor / Minor'),
  ('P4-123', 'P4', '13', 'Adyar', '171', 'D.D.Road Near Thiru.V.K Bridge', 'PCT', 'Minor / Minor / Minor'),
  ('P4-124', 'P4', '13', 'Adyar', '169', 'Govt Farm', 'PCT', 'Major / Major / Major'),
  ('P4-125', 'P4', '13', 'Adyar', '169', 'Jothiammal Nagar (Old)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-126', 'P4', '13', 'Adyar', '169', 'LDG road', 'PCT', 'Major / Major / Major'),
  ('P4-127', 'P4', '13', 'Adyar', '170', 'Ponniamman Koil Street', 'PCT', 'Minor / Minor / New Toilet'),
  ('P4-128', 'P4', '13', 'Adyar', '170', 'Gypsy Colony', 'PCT', 'Major / Minor / New Toilet'),
  ('P4-129', 'P4', '13', 'Adyar', '172', 'Race Course Road (Near Bus Stop)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-130', 'P4', '13', 'Adyar', '172', 'Link Road (Relocated to Five Furlong Road)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-131', 'P4', '13', 'Adyar', '171', 'P.S.K Salai', 'PCT', 'Major / Minor / New Toilet'),
  ('P4-132', 'P4', '13', 'Adyar', '171', 'Govindasamy Nagar (West)', 'PCT', 'Major / Major / New Toilet'),
  ('P4-133', 'P4', '13', 'Adyar', '171', 'Kamaraj Salai', 'PCT', 'Major / Minor / New Toilet'),
  ('P4-134', 'P4', '13', 'Adyar', '171', 'R.K.Mutt Road', 'PCT', 'Minor / Not Found / Minor'),
  ('P4-135', 'P4', '13', 'Adyar', '173', 'Sardar Patel Road Anna University Bus Stop in Dn- 169 (Relocated to Tiger Park Dn -173)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-136', 'P4', '13', 'Adyar', '174', 'DD Road Adjacent to Flower Market', 'PCT', 'Minor / Minor / Minor'),
  ('P4-137', 'P4', '13', 'Adyar', '174', 'Besant Nagar 2nd Avenue Near Besant Nagar Bus Stand', 'PCT', 'Minor / Minor / Minor'),
  ('P4-138', 'P4', '13', 'Adyar', '172', 'Guindy Race Course', '', 'E-Toilet / Minor / Major (No
Stability) / Major'),
  ('P4-139', 'P4', '13', 'Adyar', '173', 'Balaraman Road', 'PCT', 'Minor / Minor / Minor'),
  ('P4-140', 'P4', '13', 'Adyar', '174', 'Besent Avenue Road', 'PCT', 'New / Minor / Minor'),
  ('P4-141', 'P4', '13', 'Adyar', '174', 'Venkateswaranagar V Street', 'PCT', 'Major / Major / Major'),
  ('P4-142', 'P4', '13', 'Adyar', '175', '(Sastri Nagar 5th Cross Street) Dr. Ambedkar Nagar 65th lane (III Main Road)', 'PCT', 'Minor / Minor
(Closed) / Minor'),
  ('P4-143', 'P4', '13', 'Adyar', '178', 'Taramani 5C Bus Stop', 'PCT', 'Major / Minor / Minor'),
  ('P4-144', 'P4', '13', 'Adyar', '178', 'CSIR Road CSIR Road (Near Ascendas)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-145', 'P4', '13', 'Adyar', '174', 'MG Road LB Road Signal (Relocated to Mahatma Gandhi Road Near Adyar Depot)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-146', 'P4', '13', 'Adyar', '179', 'Astalakshmi Kovil Street', 'PCT', 'Minor / Minor / Minor'),
  ('P4-147', 'P4', '13', 'Adyar', '179', 'Vembuliyamman Kovil Street', 'PCT', 'Major / Major / Major'),
  ('P4-148', 'P4', '13', 'Adyar', '177', 'Thiruveethiamman Koil Street', 'PCT', 'Minor / Minor / Minor'),
  ('P4-149', 'P4', '13', 'Adyar', '180', 'South Avenue South Avenue (Bus Shelter)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-150', 'P4', '13', 'Adyar', '180', 'West tank road West tank road (Near Marundheeshwarar Temple)', 'PCT', 'Major / Minor / Minor'),
  ('P4-151', 'P4', '13', 'Adyar', '179', 'Thideer Nagar', 'PCT', 'Major / Major / Major'),
  ('P4-152', 'P4', '13', 'Adyar', '179', 'Besant Nagar Dobikanna', 'PCT', 'Minor / Major / Major'),
  ('P4-153', 'P4', '13', 'Adyar', '179', 'Jayaram Street', 'PCT', 'Minor / Minor / Minor'),
  ('P4-154', 'P4', '13', 'Adyar', '180', 'East Coast Road', 'PCT', 'Minor / Minor / Minor'),
  ('P4-155', 'P4', '14', 'Perungudi', '186', 'Puzhuthivakkam Bus Stand', 'PCT', 'Major / Major / New
Toilet'),
  ('P4-156', 'P4', '14', 'Perungudi', '188', 'Tambaram-Velachery main road Pallikaranai old Dumping ground', 'PCT', 'Minor / Minor / Minor'),
  ('P4-157', 'P4', '14', 'Perungudi', '188', 'Mylai Balaji Nagar Block I', 'PCT', 'Minor / Major / Major'),
  ('P4-158', 'P4', '14', 'Perungudi', '188', 'Mylai Balaji Nagar 1st Block', 'PCT', 'New / Major / Major'),
  ('P4-159', 'P4', '14', 'Perungudi', '188', 'Mylai Balaji Nagar 2nd block street', 'PCT', 'New / Major / Major'),
  ('P4-160', 'P4', '14', 'Perungudi', '188', 'Mylai Balaji Nagar Block II', 'PCT', 'Minor / Major / Major'),
  ('P4-161', 'P4', '14', 'Perungudi', '188', 'Mylai Balaji Nagar 4th block street', 'PCT', 'New / Major / Major'),
  ('P4-162', 'P4', '14', 'Perungudi', '188', 'Mylai Balaji Nagar Block III', 'PCT', 'New / Major / Major'),
  ('P4-163', 'P4', '14', 'Perungudi', '188', 'Bajanai Kovil Street', 'PCT', 'Minor / Minor / New
Toilet'),
  ('P4-164', 'P4', '14', 'Perungudi', '188', 'Madipakkam Bus Terminus', '', 'Namma
Toilet / Minor / Not Found / New
Toilet'),
  ('P4-165', 'P4', '14', 'Perungudi', '188', 'Mylai Balaji Nagar Block IV', 'PCT', 'Minor / Minor / Minor'),
  ('P4-166', 'P4', '14', 'Perungudi', '188', 'Mylai Balaji Nagar 3rd block street', 'PCT', 'New / Major / Major'),
  ('P4-167', 'P4', '14', 'Perungudi', '191', 'Pudhu Nagar Compost yard', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-168', 'P4', '14', 'Perungudi', '190', 'Karmel street', 'PCT', 'Minor / Major (Closed) / New
Toilet'),
  ('P4-169', 'P4', '14', 'Perungudi', '190', 'Kovalan Nagar', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-170', 'P4', '14', 'Perungudi', '190', 'Kovalam Nagar Burial Ground', 'PCT', 'Minor / Minor / Minor'),
  ('P4-171', 'P4', '14', 'Perungudi', '190', 'Kannabiran street', 'PCT', 'Minor / Major (Closed) / Major'),
  ('P4-172', 'P4', '14', 'Perungudi', '189', 'S. Kolathur road', 'PCT', 'Minor / Major (Closed) / New
Toilet'),
  ('P4-173', 'P4', '14', 'Perungudi', '189', 'Malligeshwarar Nagar Burial Ground', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-174', 'P4', '14', 'Perungudi', '189', 'ma Po Si Nagar Burial Ground', 'PCT', 'Minor / Minor / Minor'),
  ('P4-175', 'P4', '14', 'Perungudi', '191', 'Sai Ganesh Nagar Burial Ground', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-176', 'P4', '14', 'Perungudi', '183', 'kuppam beach', 'PCT', 'Minor / Minor / Minor'),
  ('P4-177', 'P4', '14', 'Perungudi', '183', 'Palavakkam Beach Junction of Palkalai Nagar main road', 'PCT', 'Minor / Minor / Minor'),
  ('P4-178', 'P4', '14', 'Perungudi', '181', 'Kuppam south - Beach', 'PCT', 'Minor / Major / New
Toilet'),
  ('P4-179', 'P4', '14', 'Perungudi', '181', 'Kuppam north - Beach', 'PCT', 'Minor / Minor / Minor'),
  ('P4-180', 'P4', '14', 'Perungudi', '182', 'Erikarai salai', 'PCT', 'Minor / Minor / Minor'),
  ('P4-181', 'P4', '14', 'Perungudi', '182', 'Anna nedunchalai', 'PCT', 'Minor / Minor / Minor'),
  ('P4-182', 'P4', '14', 'Perungudi', '182', 'Anna Nedunsalai', 'PCT', 'New
proposal / Not Found / New
Toilet'),
  ('P4-183', 'P4', '14', 'Perungudi', '184', 'Periyar Salai Junction with Netaji Nagar Main Road', 'PCT', 'New
proposal / Not Found / New
Toilet'),
  ('P4-184', 'P4', '14', 'Perungudi', '191', 'Jalladiyan Pettai Corporation Chennai Middle School', 'PCT', 'New
proposal / Not Found / New
Toilet'),
  ('P4-185', 'P4', '14', 'Perungudi', '191', 'Jalladiyan Pettai Corporation Chennai Middle School 1', 'PCT', 'New
proposal / Not Found / New
Toilet'),
  ('P4-186', 'P4', '14', 'Perungudi', '187', 'Madipakkam Lake', 'PCT', 'New
proposal / Vacant / New
Toilet'),
  ('P4-187', 'P4', '14', 'Perungudi', '188', 'Naicker Kuttai Lake', 'PCT', 'Minor / Not Found / New
Toilet'),
  ('P4-188', 'P4', '14', 'Perungudi', '190', 'Ambal Nagar Amman Kulam', 'PCT', 'New
proposal / Not Found / New
Toilet'),
  ('P4-189', 'P4', '15', 'Sholinganallur', '192', 'Chinma Neelankarai Kuppam Beach Near Beach Prime Toilet', 'PCT', 'Minor / Major
(Standalone) - 2
Seats / Major'),
  ('P4-190', 'P4', '15', 'Sholinganallur', '200', 'Cholan Salai Thalikulam Near 16th Ceremony Hall', 'PCT', 'New
proposal / Not Found / New
Toilet'),
  ('P4-191', 'P4', '15', 'Sholinganallur', '197', 'Gangaiamman koil colony', 'PCT', 'Major / Minor
(Standalone) / Minor'),
  ('P4-192', 'P4', '15', 'Sholinganallur', '198', 'Gangaiamman koil street (Near dn. Office)', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-193', 'P4', '15', 'Sholinganallur', '194', 'GOWRI AMMAN KOVIL STREET JN. OF 4TH STREET', 'PCT', 'Major / Minor / Minor'),
  ('P4-194', 'P4', '15', 'Sholinganallur', '200', 'Jawahar nagar 3rd street end', 'PCT', 'Minor / Minor / Minor'),
  ('P4-195', 'P4', '15', 'Sholinganallur', '192', 'Kabalieswarar Nagar Beach Road Near Beach', 'PCT', 'Minor / Major / Major'),
  ('P4-196', 'P4', '15', 'Sholinganallur', '198', 'Kaliamman koil street near amma Unavagam', 'PCT', 'Major / Major (Closed) / New
Toilet'),
  ('P4-197', 'P4', '15', 'Sholinganallur', '198', 'Karapakkam Burial Ground (Christian)', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-198', 'P4', '15', 'Sholinganallur', '198', 'Karapakkam Burial Ground (Hindu)', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-199', 'P4', '15', 'Sholinganallur', '198', 'Karapakkam Burial Ground(Muslims)', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-200', 'P4', '15', 'Sholinganallur', '197', 'KUDUMIYANDI THOPPU, School road near Amma Unavagam', 'PCT', 'Minor / Minor / Minor'),
  ('P4-201', 'P4', '15', 'Sholinganallur', '199', 'Nedunchezhian street Shopping complex', 'PCT', 'Major / Minor / Minor'),
  ('P4-202', 'P4', '15', 'Sholinganallur', '195', 'OKKIYAM BUS STOP OMR', '', 'E-Toilet / Major / Minor
(Standalone) / Major'),
  ('P4-203', 'P4', '15', 'Sholinganallur', '199', 'OMR Opp to Umadri Mandabam', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-204', 'P4', '15', 'Sholinganallur', '197', 'Panaiyur kuppam Beach North (Ladies) Near beach', 'PCT', 'Minor / Minor / Minor'),
  ('P4-205', 'P4', '15', 'Sholinganallur', '197', 'Panaiyur kuppam Beach South (Gents) near beach', 'PCT', 'Minor / Minor / Minor'),
  ('P4-206', 'P4', '15', 'Sholinganallur', '197', 'Panaiyur kuppam Beach South (Ladies) near beach', 'PCT', 'Minor / Minor / Minor'),
  ('P4-207', 'P4', '15', 'Sholinganallur', '200', 'Panchayat office main road near VAO office', 'PCT', 'Minor / Minor / Minor'),
  ('P4-208', 'P4', '15', 'Sholinganallur', '193', 'Pandian Salai Near Devi Karumariyamman Kovil', '', 'Standalone
Urinal / Minor / Major / Major'),
  ('P4-209', 'P4', '15', 'Sholinganallur', '199', 'PARAMESWARAN NAGAR Infosys back side', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-210', 'P4', '15', 'Sholinganallur', '192', 'PERIYA NEELANGARAI KUPPAM (SOUTH), near beach', 'PCT', 'Minor / Minor / Minor'),
  ('P4-211', 'P4', '15', 'Sholinganallur', '192', 'Periya Neelankarai Kuppam Beach Near Blue Beach Prime Toilet', 'PCT', 'Minor / Major / Major'),
  ('P4-212', 'P4', '15', 'Sholinganallur', '198', 'Periya palayathamman koil street Near koil', 'PCT', 'Minor / Minor / Minor'),
  ('P4-213', 'P4', '15', 'Sholinganallur', '200', 'Pondicherry pattai salai near burial ground', 'PCT', 'Minor / Minor / Minor'),
  ('P4-214', 'P4', '15', 'Sholinganallur', '197', 'RAJIV GANDHI NAGAR, 4th STREET near Burial ground', 'PCT', 'Minor / Minor / Minor'),
  ('P4-215', 'P4', '15', 'Sholinganallur', '198', 'Rajiv Gandhi Salai Near Dollor park', '', 'Standalone
Urinal / Minor / Major / Major'),
  ('P4-216', 'P4', '15', 'Sholinganallur', '199', 'Rajiv Gandhi Salai Near Shopping complex', '', 'Standalone
Urinal / Minor / Minor / Minor'),
  ('P4-217', 'P4', '15', 'Sholinganallur', '199', 'Sathyananimuthu street (Ladies) near Christian burial ground', 'PCT', 'Major / Minor (Closed) / Minor'),
  ('P4-218', 'P4', '15', 'Sholinganallur', '199', 'School street (Near MLA office)', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-219', 'P4', '15', 'Sholinganallur', '200', 'TNSCB 1st main road, Semmencherry', 'PCT', 'Minor / Minor / Minor'),
  ('P4-220', 'P4', '15', 'Sholinganallur', '200', 'TNSCB tenement 7th avenue jn. Of 1st main road', 'PCT', 'Minor / Minor / Minor'),
  ('P4-221', 'P4', '15', 'Sholinganallur', '200', 'Veeravanjinathan salai near pond', 'PCT', 'Major / Minor / Minor'),
  ('P4-222', 'P4', '15', 'Sholinganallur', '197', 'VGP 2nd Main Road Near Uthandi Beach', 'PCT', 'Minor / Minor / Minor'),
  ('P4-223', 'P4', '11', 'Valasaravakkam', '152', 'Thiruvalluvar Salai Near Amma', 'PCT', 'Minor / Minor / Minor'),
  ('P4-224', 'P4', '13', 'Adyar', '169', '(Relocated to Taluk Office Road)', 'PCT', 'Minor / Minor / Minor'),
  ('P4-225', 'P4', '13', 'Adyar', '169', 'Sardar Patel Road Gandhi Mandapam', 'PCT', 'Minor / Minor / Minor'),
  ('P4-226', 'P4', '13', 'Adyar', '171', '(R.K.Nagar 1 St Main Road) South', 'PCT', 'Minor / Minor / Minor'),
  ('P4-227', 'P4', '13', 'Adyar', '173', 'Sardar Patel Road Anna University Bus', 'PCT', 'Minor / Minor / Minor'),
  ('P4-228', 'P4', '13', 'Adyar', '175', '(Sastri Nagar 5th Cross Street) Dr.', 'PCT', 'Minor / Minor (Closed) / Minor'),
  ('P4-229', 'P4', '13', 'Adyar', '174', 'MG Road LB Road Signal (Relocated to', 'PCT', 'Minor / Minor / Minor'),
  ('P4-230', 'P4', '11', 'Valasaravakkam', '143', 'Sri Ram Nagar Main road Near', 'PCT', 'Minor / Demolished / New'),
  ('P4-231', 'P4', '12', 'Alandur', '162', 'Thillai Ganga Nagar Burial', 'PCT', 'Minor / Minor (Closed) / Major')
on conflict (id) do nothing;

-- seed a matching blank status row for every site
insert into site_status (site_id, status)
select id, 'unknown' from sites
on conflict (site_id) do nothing;